import type { Metadata } from "next";
import localFont from 'next/font/local'
import "@/styles/tailwind.css";

const satoshi = localFont({
  variable: '--font-satoshi',
  src: [
    {
      path: '../styles/Satoshi-Variable.woff2',
    },
    {
      path: '../styles/Satoshi-VariableItalic.woff2',
      style: 'italic',
    },
  ],
  display: 'swap',
  preload: true,
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.className} dark`}>{children}</body>
    </html>
  );
}
